import { useState } from 'react'
import { useParams, Link } from 'react-router-dom'
import { ArrowLeft, BellRing, CheckCircle2, MapPin, Navigation, Phone, Printer, ShieldCheck, Truck, AlertTriangle, Camera } from 'lucide-react'
import { rescueRequests, incidentTimeline } from '../mocks/mockData'
import { formatCurrency } from '../lib/format'
import { PageHeader } from '../components/ui/PageHeader'
import { SectionCard } from '../components/ui/SectionCard'
import { StatusBadge } from '../components/ui/StatusBadge'
import { EmptyState } from '../components/ui/EmptyState'
export function RescueRequestDetailPage() {
  const { id } = useParams()
  const request = rescueRequests.find((item) => item.id === id)
  const [confirmed, setConfirmed] = useState(false)
  if (!request) return <EmptyState title="Không tìm thấy yêu cầu cứu hộ" description="Mã ca không nằm trong bộ dữ liệu demo."/>
  const stepIcons = [CheckCircle2, ShieldCheck, Phone, Navigation, MapPin]
  return <><PageHeader eyebrow="YÊU CẦU CỨU HỘ / CHI TIẾT" title={'Chi tiết yêu cầu cứu hộ #' + request.id} description="Theo dõi tiến độ xử lý và điều phối đối tác cứu hộ." actions={<><button className="button button-white" onClick={() => window.print()}><Printer size={15}/> In Phiếu</button><button className="button button-blue" onClick={() => setConfirmed(!confirmed)}><CheckCircle2 size={15}/>{confirmed ? 'Đã xác nhận' : 'Xác nhận xử lý'}</button></>}/><div className="request-summary"><StatusBadge>{request.status}</StatusBadge><span>Thời gian tạo: 24/10/2024 · {request.time}</span><span className="red-text">Khẩn cấp cấp độ 1</span></div>
    <div className="detail-grid"><div className="detail-main"><SectionCard title="Tiến độ can thiệp trực tiếp" subtitle="Quy trình điều động cứu hộ theo chuẩn nghiệp vụ"><div className="timeline">{incidentTimeline.map(({ name, time }, index) => { const Icon = stepIcons[index]; return <div className={'timeline-step ' + (index < 4 ? 'complete' : '')} key={name}><div className="timeline-dot"><Icon size={16}/></div><small>{time}</small><b>{name}</b><span>{index === 4 ? 'ETA 8 phút' : 'Đã cập nhật'}</span></div> })}</div></SectionCard>
      <SectionCard title="Thông tin sự cố & Hiện trường thực tế"><div className="incident-grid"><div className="info-panel"><span className="mini-heading">ĐỐI TƯỢNG SỰ CỐ</span><h3>{request.incident}</h3><p>Yêu cầu hỗ trợ kỹ thuật tại hiện trường. Điều phối viên đã liên hệ xác minh vị trí và triệu chứng sự cố.</p></div><div className="info-panel"><span className="mini-heading">CHUẨN ĐOÁN SƠ BỘ</span><h3>Hư hỏng bộ phận, bổ sung cứu hộ</h3><p>Khách hàng được tư vấn an toàn và chờ đội cứu hộ đến.</p></div><div className="info-panel warm"><span className="mini-heading">VỊ TRÍ GẶP NẠN</span><h3>{request.location}</h3><p>Gần trung tâm thành phố · Đà Nẵng</p></div><div className="info-panel cool"><span className="mini-heading">ĐỘI CỨU HỘ ĐƯỢC ĐIỀU PHỐI</span><h3>{request.team}</h3><p>Đã nhận lệnh, đang cập nhật vị trí GPS.</p></div></div><div className="mock-map small-map"><div className="map-road road-one"/><div className="map-road road-two"/><div className="map-river"/><span className="map-city">ĐÀ NẴNG</span><span className="map-pin center"><MapPin size={19}/></span><span className="map-tag">Hiện trường · {request.location}</span></div><div className="photo-grid">{['Hiện trường sự cố','Góc chụp tổng thể','Biển số & tình trạng xe'].map((name, index) => <div className={'photo-placeholder photo-' + index} key={name}><Camera size={25}/><span>{name}</span></div>)}</div><div className="alert-box"><AlertTriangle size={18}/><span><b>Ghi chú khẩn từ điều phối viên:</b> Khách đang đỗ sát làn đường, ưu tiên an toàn hiện trường và xác nhận tình trạng phương tiện trước khi xử lý.</span></div></SectionCard>
      <SectionCard title="Báo giá dịch vụ & Chi phí cứu hộ" subtitle="Minh bạch chi phí cứu hộ được tính tự động từ loại dịch vụ và thời gian"><div className="quote-lines"><div><span>{request.service}</span><b>{formatCurrency(request.amount ? request.amount * .55 : 0)}</b></div><div><span>Chi phí di chuyển & hỗ trợ kỹ thuật</span><b>{formatCurrency(request.amount ? request.amount * .25 : 0)}</b></div><div><span>Phụ phí ca đêm / cao điểm & vật tư</span><b>{formatCurrency(request.amount ? request.amount * .2 : 0)}</b></div></div><div className="total-row"><span>Tổng phí dịch vụ dự kiến</span><strong>{formatCurrency(request.amount)}</strong></div></SectionCard></div>
      <div className="detail-side"><SectionCard title="Chủ xe / Khách hàng"><div className="profile-line"><span className="avatar">LL</span><div><h3>{request.customer}</h3><p>{request.phone}</p></div></div><div className="key-values"><div><span>Số điện thoại</span><b>{request.phone}</b></div><div><span>Hạng thành viên</span><b>Hội viên Vàng</b></div><div><span>Vị trí</span><b>{request.location}</b></div></div><div className="button-pair"><a className="button button-blue" href={'tel:' + request.phone.replaceAll(' ', '')}><Phone size={14}/> Gọi khách</a><button className="button button-white" onClick={() => alert('Tin nhắn demo đã được ghi nhận.')}><BellRing size={14}/> Nhắn tin</button></div></SectionCard><SectionCard title="Phương tiện gặp nạn"><div className="key-values"><div><span>Model</span><b>{request.vehicle}</b></div><div><span>Biển số</span><b>{request.plate}</b></div><div><span>Loại xe</span><b>Ô tô cá nhân</b></div><div><span>Hạng thành viên</span><b>Ưu tiên</b></div></div></SectionCard><SectionCard title="Đội tác cứu hộ tiếp nhận"><div className="profile-line"><span className="avatar blue"><Truck size={20}/></span><div><h3>{request.team}</h3><p>Đã tiếp nhận · Đang di chuyển</p></div></div><div className="key-values"><div><span>Loại xe</span><b>Xe cứu hộ chuyên dụng</b></div><div><span>Biển số</span><b>43C-118.58</b></div><div><span>Hotline tài xế</span><b>0915 998 776</b></div></div><button className="button button-soft full-width" onClick={() => alert('Vị trí GPS demo hiển thị tại bản đồ điều hành.')}> <MapPin size={14}/> Gọi tài xế / Xem GPS</button></SectionCard><SectionCard title="Thao tác điều hành ca trực"><div className="stack-actions"><button onClick={() => alert('Lệnh điều phối demo đã được ghi nhận.')}><Navigation size={16}/> Điều phối viên xem vị trí <span>›</span></button><button onClick={() => alert('Thông báo demo đã được ghi nhận.')}><BellRing size={16}/> Gửi thông báo khẩn cấp <span>›</span></button><Link to="/map"><MapPin size={16}/> Xem bản đồ GPS <span>›</span></Link><button className="danger" onClick={() => setConfirmed(false)}><AlertTriangle size={16}/> Hủy yêu cầu cứu hộ <span>›</span></button></div></SectionCard><Link className="back-link" to="/requests"><ArrowLeft size={15}/> Quay lại danh sách yêu cầu</Link></div></div></>
}


