import { useMemo, useState } from 'react'
import { Search, Send, SlidersHorizontal } from 'lucide-react'
import { reviews, rescuers, reviewStats, ratingDistribution } from '../mocks/mockData'
import { initials } from '../lib/format'
import { PageHeader } from '../components/ui/PageHeader'
import { SectionCard } from '../components/ui/SectionCard'
import { StatCard } from '../components/ui/StatCard'
import { StatusBadge } from '../components/ui/StatusBadge'
import { EmptyState } from '../components/ui/EmptyState'
export function ReviewsPage() {
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('Tất cả'); const [replied, setReplied] = useState<Record<string, boolean>>({})
  const rows = useMemo(() => reviews.filter((item) => (item.name + item.id + item.service).toLocaleLowerCase('vi').includes(query.toLocaleLowerCase('vi')) && (filter === 'Tất cả' || (filter === '5 sao' ? item.rating === 5 : filter === 'Dưới 3 sao' ? item.rating < 3 : item.status === 'Đang xử lý CSKH'))), [query, filter])
  return <><PageHeader eyebrow="QUALITY ASSURANCE / CSAT" title="Đánh giá & Phản hồi Dịch vụ" description="Theo dõi chỉ số hài lòng của khách hàng (CSAT), phân hồi chất lượng đội xe cứu hộ và xử lý khiếu nại dịch vụ." actions={<button className="button button-blue" onClick={() => alert('Báo cáo CSAT demo chưa có tệp xuất.')}>Xuất báo cáo PDF / Excel</button>}/><div className="stat-grid cols-4">{reviewStats.map((item) => <StatCard key={item.label} {...item}/>)}</div><div className="filter-row service-filter"><label className="search-field"><Search size={16}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Tìm theo tên khách hàng, mã đơn..." /></label><label className="select-field"><SlidersHorizontal size={15}/><select value={filter} onChange={(e) => setFilter(e.target.value)}>{['Tất cả','5 sao','Dưới 3 sao','Đang xử lý CSKH'].map((item) => <option key={item}>{item}</option>)}</select></label></div><div className="review-layout"><div><SectionCard title="Phân bố xếp hạng sao" subtitle="03 / 2024"><div className="rating-score"><strong>4.9</strong><span>★ ★ ★ ★ ★</span><small>99.2% tích cực</small></div>{ratingDistribution.map(({star, value}) => <div className="rating-line" key={star}><span>{star} sao</span><i><b style={{ width: value + '%' }}/></i><strong>{value}%</strong></div>)}</SectionCard><SectionCard title="Đội cứu hộ dẫn đầu CSAT"><div className="leader-list">{rescuers.slice(0, 3).map((item, index) => <div key={item.id}><span>{index + 1}</span><b>{item.name}</b><small>★ {item.rating}</small></div>)}</div></SectionCard></div><div><div className="section-heading outside"><div><h2>Danh sách đánh giá gần đây</h2><p>Real-time feed · Sắp xếp: Mới nhất trước</p></div></div>{rows.length ? rows.map((item) => <article className={'review-card' + (item.rating < 3 ? ' negative' : '')} key={item.id}><div className="review-top"><span className="avatar">{initials(item.name)}</span><div><b>{item.name}</b><small>{item.id} · 2 giờ trước</small></div><span className="stars">{'★'.repeat(item.rating)}{'☆'.repeat(5 - item.rating)}</span><StatusBadge>{replied[item.id] ? 'Đã phản hồi' : item.status}</StatusBadge></div><blockquote>“{item.text}”</blockquote><div className="review-footer"><span>Dịch vụ: <b>{item.service}</b></span><span>Đội cứu hộ: <b>{item.team}</b></span><button onClick={() => { const response = window.prompt('Nhập phản hồi gửi khách hàng (dữ liệu demo):'); if (response?.trim()) setReplied({ ...replied, [item.id]: true }) }}><Send size={14}/> Phản hồi khách</button></div></article>) : <EmptyState/>}</div></div></>
}



