import { useMemo, useState } from 'react'
import { Check, History, Search, Settings2, SlidersHorizontal } from 'lucide-react'
import { services, serviceStats } from '../mocks/mockData'
import { formatCurrency } from '../lib/format'
import { PageHeader } from '../components/ui/PageHeader'

import { StatCard, ServiceIcon } from '../components/ui/StatCard'
import { EmptyState } from '../components/ui/EmptyState'
export function ServicesPage() {
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('Tất cả'); const [enabled, setEnabled] = useState<Record<string, boolean>>({})
  const rows = useMemo(() => services.filter((item) => item.name.toLocaleLowerCase('vi').includes(query.toLocaleLowerCase('vi')) && (filter === 'Tất cả' || (filter === 'Đang hoạt động' ? enabled[item.id] !== false : enabled[item.id] === false))), [query, filter, enabled])
  return <><PageHeader eyebrow="CATALOG / 6 DỊCH VỤ" title="Quản lý Dịch vụ Cứu Hộ" description="Cấu hình danh mục dịch vụ khẩn cấp, bảng cước quy định, thiết bị cứu hộ chuyên dụng và năng lực hỗ trợ trên toàn hệ thống." actions={<button className="button button-blue" onClick={() => alert('Tính năng thêm dịch vụ sẽ khả dụng khi kết nối backend.')}>+ Thêm dịch vụ mới</button>}/><div className="stat-grid cols-4">{serviceStats.map((item) => <StatCard key={item.label} {...item}/>)}</div><div className="filter-row service-filter"><label className="search-field"><Search size={16}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Tìm dịch vụ, mã cước, thiết bị cứu hộ..." /></label><label className="select-field"><SlidersHorizontal size={15}/><select value={filter} onChange={(e) => setFilter(e.target.value)}>{['Tất cả','Đang hoạt động','Đã tắt'].map((item) => <option key={item}>{item}</option>)}</select></label><span className="soft-pill">Tất cả ({services.length})</span></div><div className="services-grid">{rows.map((item) => <article className="service-card" key={item.id}><div className="service-card-top"><span className="icon-box blue"><ServiceIcon name={item.icon}/></span><div><small>Mã: {item.id}</small><span>{enabled[item.id] === false ? 'Đã tạm tắt' : 'Đang hoạt động'}</span></div><button className={'toggle ' + (enabled[item.id] === false ? '' : 'on')} onClick={() => setEnabled({ ...enabled, [item.id]: enabled[item.id] === false })} aria-label={'Bật tắt ' + item.name}><i/></button></div><h3>{item.name}</h3><p>{item.description}</p><div className="service-price"><small>Giá dịch vụ tham khảo</small><strong>{formatCurrency(item.price)} <em>/ {item.unit}</em></strong></div><div className="service-detail"><span><Check size={14}/> Thiết bị tiêu chuẩn</span><b>{item.equipment}</b></div><div className="service-meta"><span>Đã thực hiện: <b>{item.jobs.toLocaleString('vi-VN')} đơn</b></span><span>★ <b>{item.rating.toFixed(1)} / 5.0</b></span></div><div className="service-actions"><button onClick={() => alert('Lịch sử cước demo: ' + item.name)}><History size={14}/> Xem lịch sử cước</button><button onClick={() => alert('Cấu hình demo: ' + item.name)}><Settings2 size={14}/> Sửa cấu hình</button></div></article>)}</div>{!rows.length && <EmptyState/>}<div className="info-ribbon"><span>◉</span><div><b>Chính Sách Phụ Thu Giờ Cao Điểm & Thời Tiết Cực Đoan</b><small>Tự động điều chỉnh hệ số cước từ 1.2x – 1.5x vào khung giờ 22:00 – 05:00 sáng hoặc khi có cảnh báo mưa lớn, mật độ giao thông tăng cao.</small></div><button className="button button-white" onClick={() => alert('Thiết lập phụ thu là dữ liệu demo.')}>Thiết lập quy tắc</button></div></>
}



